language: en
pipeline:
- name: "SpacyNLP"
  model: en_core_web_md
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "SklearnIntentClassifier"
- name: "EntitySynonymMapper"

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
  nlu_threshold: 0.4
  core_threshold: 0.4
  fallback_action_name: 'action_default_fallback'